USE gastos_empresariales;

CREATE TABLE IF NOT EXISTS areas (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    codigo_centro_costo VARCHAR(30) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    jefe_usuario_id INT UNSIGNED NULL DEFAULT NULL,
    deleted_at DATETIME NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS usuarios (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    correo VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    rol_id INT UNSIGNED NOT NULL,
    area_id INT UNSIGNED NULL DEFAULT NULL,
    activo TINYINT(1) NOT NULL DEFAULT 1,
    deleted_at DATETIME NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (rol_id) REFERENCES roles(id),
    FOREIGN KEY (area_id) REFERENCES areas(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE areas ADD CONSTRAINT fk_areas_jefe FOREIGN KEY (jefe_usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS proveedores (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    rfc VARCHAR(15) NOT NULL UNIQUE,
    nombre VARCHAR(255) NOT NULL,
    deleted_at DATETIME NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS presupuestos (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    area_id INT UNSIGNED NOT NULL,
    anio YEAR NOT NULL,
    mes TINYINT UNSIGNED NOT NULL,
    monto_asignado DECIMAL(15,2) NOT NULL,
    created_by INT UNSIGNED NOT NULL,
    updated_by INT UNSIGNED NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_presupuesto (area_id, anio, mes),
    FOREIGN KEY (area_id) REFERENCES areas(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS gastos (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    folio VARCHAR(20) NOT NULL UNIQUE,
    uuid_cfdi CHAR(36) NOT NULL UNIQUE,
    proveedor_id INT UNSIGNED NULL DEFAULT NULL,
    area_id INT UNSIGNED NOT NULL,
    capturado_por INT UNSIGNED NOT NULL,
    estado_id INT UNSIGNED NOT NULL DEFAULT 1,
    fecha_emision DATE NOT NULL,
    fecha_carga DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_envio_aprobacion DATETIME NULL DEFAULT NULL,
    fecha_finalizacion DATETIME NULL DEFAULT NULL,
    subtotal DECIMAL(15,2) NOT NULL,
    iva DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    total DECIMAL(15,2) NOT NULL,
    concepto VARCHAR(500),
    categoria_id INT UNSIGNED NULL DEFAULT NULL,
    cuenta_id INT UNSIGNED NULL DEFAULT NULL,
    xml_path VARCHAR(500),
    moneda CHAR(3) NOT NULL DEFAULT 'MXN',
    rfc_emisor VARCHAR(15),
    rfc_receptor VARCHAR(15),
    forma_pago VARCHAR(5),
    uso_cfdi VARCHAR(10),
    finalizado_por INT UNSIGNED NULL DEFAULT NULL,
    aprobado_por INT UNSIGNED NULL DEFAULT NULL,
    rechazado_por INT UNSIGNED NULL DEFAULT NULL,
    motivo_rechazo TEXT NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (proveedor_id) REFERENCES proveedores(id),
    FOREIGN KEY (area_id) REFERENCES areas(id),
    FOREIGN KEY (capturado_por) REFERENCES usuarios(id),
    FOREIGN KEY (estado_id) REFERENCES estatus_gasto(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS gasto_detalles (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    gasto_id INT UNSIGNED NOT NULL,
    descripcion VARCHAR(500) NOT NULL,
    cantidad DECIMAL(10,4) NOT NULL,
    precio_unitario DECIMAL(15,2) NOT NULL,
    importe DECIMAL(15,2) NOT NULL,
    FOREIGN KEY (gasto_id) REFERENCES gastos(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS bitacora_auditoria (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    usuario_id INT UNSIGNED NULL,
    accion VARCHAR(100) NOT NULL,
    entidad VARCHAR(100) NOT NULL,
    entidad_id INT UNSIGNED NULL,
    valor_anterior JSON NULL DEFAULT NULL,
    valor_nuevo JSON NULL DEFAULT NULL,
    ip VARCHAR(45),
    user_agent VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
